exclude: >
    (?x)^(
      demo/.*|
      tests/notebooks/.*|
    )$
repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    # - id: check-json
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.32.0
    hooks:
    - id: pyupgrade
      args: ["--py36-plus"]

  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
    - id: autoflake
      args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      args: [ "--ignore", "E501, W503, E402", ]

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      # isort needs the 'black' profile when used in combination with black
      # See https://github.com/PyCQA/isort/issues/1518
    - id: isort
      args: ["--profile", "black"]

  - repo: https://github.com/mwouts/jupytext
    rev: v1.13.8  # CURRENT_TAG/COMMIT_HASH
    hooks:
      - id: jupytext
        args: [ --sync, --pipe, black ]
        additional_dependencies:
          - black==22.3.0 # Matches hook

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.3.1
    hooks:
      - id: nbqa-black
      - id: nbqa-pyupgrade
        args: [ --py36-plus ]
      - id: nbqa-isort
      - id: nbqa-flake8
        args: [ "--extend-ignore=E501,W503,E402",]
